[project]
name = "python"
version = "0.1.0"
description = "Adventjs solutions in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.8.1",
]
